# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include_dir_list automations
script: !include scripts.yaml
scene: !include scenes.yaml
group: !include groups.yaml
template: !include templates.yaml
logger: !include logger.yaml

lovelace:
  dashboards: !include dashboards.yaml
