# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
group: !include groups.yaml
template: !include templates.yaml

logger:
  filters:
    homeassistant.loader:
      - "We found a custom integration presence_simulation which has not been tested by Home Assistant."
      - "We found a custom integration hacs which has not been tested by Home Assistant."
      - "We found a custom integration climate_scheduler which has not been tested by Home Assistant."
    custom_components.presence_simulation:
      - "Presence simulation switch switch.presence_simulation_lights is not on, can't be turned off"

lovelace:
  dashboards:
    mode-yaml:
      mode: yaml
      filename: dashboards/mode.yaml
      title: Mode
      icon: mdi:apple-keyboard-command
      show_in_sidebar: true
    light-switches-yaml:
      mode: yaml
      filename: dashboards/lights-switches.yaml
      title: Lights - Switches
      icon: mdi:light-switch
      show_in_sidebar: true
    heating-thermostats-yaml:
      mode: yaml
      filename: dashboards/heating-thermostats.yaml
      title: Heating - Thermostats
      icon: mdi:thermostat
      show_in_sidebar: true
    heating-schedules-yaml:
      mode: yaml
      filename: dashboards/heating-schedules.yaml
      title: Heating - Schedules
      icon: mdi:heating-coil
      show_in_sidebar: true
    shutters-rollers-yaml:
      mode: yaml
      filename: dashboards/shutters-rollers.yaml
      title: Shutters - Rollers
      icon: mdi:window-shutter
      show_in_sidebar: true
    batteries-yaml:
      mode: yaml
      filename: dashboards/batteries.yaml
      title: Batteries
      icon: mdi:battery-50
      show_in_sidebar: true
    fire-tv-yaml:
      mode: yaml
      filename: dashboards/fire-tv.yaml
      title: Fire TV
      icon: mdi:television
      show_in_sidebar: true
    alarms-yaml:
      mode: yaml
      filename: dashboards/alarms.yaml
      title: Alarms
      icon: mdi:alarm-light-outline
      show_in_sidebar: true
    audit-yaml:
      mode: yaml
      filename: dashboards/audit.yaml
      title: Audit
      icon: mdi:bug-check-outline
      show_in_sidebar: true
    map-yaml:
      mode: yaml
      filename: dashboards/map.yaml
      title: Map
      icon: mdi:map
      show_in_sidebar: true
#    overview-yaml:
#      mode: yaml
#      filename: dashboards/overview.yaml
#      title: Overview
#      icon: mdi:view-dashboard
#      show_in_sidebar: true

#lovelace:
#  resource_mode: yaml
#  resources:
#    - url: /climate_scheduler/static/climate-scheduler-card.js?v=1.14.12
#      type: module
#  dashboards:
#    lovelace:
#      mode: yaml
#      filename: ui-lovelace.yaml
#      title: Overview
#      icon: mdi:view-dashboard
#      show_in_sidebar: true
#    lovelace-home:
#      mode: yaml
#      filename: lovelace/dashboards/home.yaml
#      title: Home
#      icon: mdi:home
#      show_in_sidebar: true

#    lovelace-security:
#      mode: yaml
#      filename: lovelace/dashboards/security.yaml
#     title: Security
#     icon: mdi:shield-home
#     show_in_sidebar: true
