
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
group: !include groups.yaml
template: !include templates.yaml

logger:
  filters:
    homeassistant.loader: warning
      - "We found a custom integration presence_simulation which has not been tested by Home Assistant."
      - "We found a custom integration hacs which has not been tested by Home Assistant."
      - "We found a custom integration climate_scheduler which has not been tested by Home Assistant."
    custom_components.presence_simulation: warning
      - "Presence simulation switch switch.presence_simulation_lights is not on, can't be turned off"
