version: 4
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto:1883
  user: addons
  password: sohmaep6thea1Ia7gieshaibahz4doh9ieVeechoPahRo4eer7thiem6eex0lei0
serial:
  baudrate: 115200
  rtscts: false
  port: >-
    /dev/serial/by-id/usb-Itead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_V2_82611b2ecd73ef1189a6c274d9b539e6-if00-port0
  adapter: ember
advanced:
  log_level: info
  channel: 25
  network_key:
    - 115
    - 243
    - 41
    - 129
    - 172
    - 89
    - 46
    - 255
    - 137
    - 137
    - 52
    - 145
    - 90
    - 59
    - 218
    - 91
  pan_id: 34477
  ext_pan_id:
    - 94
    - 103
    - 216
    - 1
    - 152
    - 115
    - 195
    - 206
  last_seen: ISO_8601
frontend:
  enabled: true
  port: 8099
homeassistant:
  enabled: true
devices:
  '0x08ddebfffef3647d':
    friendly_name: Tom's Office Button near Window
  '0x94b216fffe8c4a10':
    friendly_name: Living Room TV Light
  '0x08fd52fffe07728b':
    friendly_name: Living Room Dbl Light
  '0x04e3e5fffea35360':
    friendly_name: Living Room Main Light
  '0x04e3e5fffeec4153':
    friendly_name: Living Room Couch Light
  '0xbc8d7efffe9c9f95':
    friendly_name: Ground Floor Corridor Light
  '0x94b216fffea09dcf':
    friendly_name: Basement Corridor Light
  '0x94b216fffe8cc45c':
    friendly_name: Store Room Light
  '0x7cc6b6fffecabc06':
    friendly_name: First Floor Corridor Light
  '0x04e3e5fffea24c7c':
    friendly_name: Tom’s Office Light
  '0x04e3e5fffed2370b':
    friendly_name: Bedroom Main Light
  '0x94b216fffe8c2067':
    friendly_name: Entryway Light
  '0x94b216fffea099d1':
    friendly_name: Anuradha’s Room Main Light
  '0xfc4d6afffe639245':
    friendly_name: Ironing Room Main Light
  '0x7cc6b6fffec93870':
    friendly_name: Ironing Room Wall Light
  '0x1cc089fffece7108':
    friendly_name: Staircase Corner Light
  '0x08b95ffffe5951e9':
    friendly_name: Server Room Light
  '0x08b95ffffe6c1234':
    friendly_name: Laundry Room Main Light
  '0x08b95ffffeb3de72':
    friendly_name: Laundry Room Mirror Light
  '0x08b95ffffe596127':
    friendly_name: Bedroom Left Light
  '0x1cc089fffece6a7f':
    friendly_name: Bedroom Right Light
  '0x1cc089fffecddd13':
    friendly_name: Bedroom Mirror Light
  '0xfc4d6afffe5027d5':
    friendly_name: Heating Room Light
  '0x08b95ffffec72d5c':
    friendly_name: Maheeka’s Office Light
  '0xc09b9efffed42975':
    friendly_name: Terrace Door Open Sensor
  '0x94a081fffed71e48':
    friendly_name: Bathroom Main Light
  '0x1cc089fffed8079d':
    friendly_name: Kitchen Light
  '0xfc4d6afffe6e0864':
    friendly_name: Attic Stairs Light
  '0x4c97a1fffece1dbd':
    friendly_name: Bathroom Dbl Light Sinks
  '0x1cc089fffe2466cb':
    friendly_name: Attic Store Room
  '0x08b95ffffe58e16b':
    friendly_name: Anuradha’s Room Stars
  '0xc09b9efffe8462b3':
    friendly_name: Kitchen Heating
    thermostat_unit: celsius
  '0xc09b9efffe845e2d':
    friendly_name: Maheeka‘s Office Heating Back
  '0x8c73dafffe846d06':
    friendly_name: Kitchen Thermometer
availability:
  enabled: true
